name: Main

on: [push]

jobs:
  default-sdk-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: GuillaumeFalourd/windows10-sdk-action@main

  specific-sdk-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: GuillaumeFalourd/windows10-sdk-action@main
        with:
          sdk-version: 19041