name: Security Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  horusec-security:
    name: horusec-security
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Check out code into the directory
        uses: actions/checkout@v2.3.4
      - name: Running Horusec Security Download latest version
        shell: bash
        run: |
          curl -fsSL https://horusec.io/bin/install.sh | bash
          horusec start -p="./"