name: Specific SDK version Workflow

on: [push]

jobs:
  specific-sdk-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@main
        with:
          sdk-version: 19041

      - name: Build new SDK
        shell: bash
        run: |
          cmake -DCMAKE_SYSTEM_VERSION=10.0.19041.0
          cmake --build .

  20348-sdk-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@main
        with:
          sdk-version: 20348

      - name: Build new SDK
        shell: bash
        run: |
          cmake -DCMAKE_SYSTEM_VERSION=10.0.20348.0
          cmake --build .