name: Specific SDK version Workflow

on: [push]

jobs:
  
  specific-sdk-version-16299:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@main
        with:
          sdk-version: 16299

      - name: Build new SDK
        shell: bash
        run: |
          cmake -DCMAKE_SYSTEM_VERSION=10.0.16299.0
          cmake --build .

  specific-sdk-version-17763:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@main
        with:
          sdk-version: 17763

      - name: Build new SDK
        shell: bash
        run: |
          cmake -DCMAKE_SYSTEM_VERSION=10.0.17763.0
          cmake --build .

  specific-sdk-version-18362:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@main
        with:
          sdk-version: 18362

      - name: Build new SDK
        shell: bash
        run: |
          cmake -DCMAKE_SYSTEM_VERSION=10.0.18362.0
          cmake --build .

  specific-sdk-version-19041:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@main
        with:
          sdk-version: 19041

      - name: Build new SDK
        shell: bash
        run: |
          cmake -DCMAKE_SYSTEM_VERSION=10.0.19041.0
          cmake --build .

  specific-sdk-version-20348:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@main
        with:
          sdk-version: 20348

      - name: Build new SDK
        shell: bash
        run: |
          cmake -DCMAKE_SYSTEM_VERSION=10.0.20348.0
          cmake --build .

  specific-sdk-version-22000:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@main
        with:
          sdk-version: 22000

      - name: Build new SDK
        shell: bash
        run: |
          cmake -DCMAKE_SYSTEM_VERSION=10.0.22000.0
          cmake --build .

  specific-sdk-version-22621:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@main
        with:
          sdk-version: 22621

      - name: Build new SDK
        shell: bash
        run: |
          cmake -DCMAKE_SYSTEM_VERSION=10.0.22621.0
          cmake --build .

  specific-sdk-version-26100:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@main
        with:
          sdk-version: 26100

      - name: Build new SDK
        shell: bash
        run: |
          cmake -DCMAKE_SYSTEM_VERSION=10.0.26100.0
          cmake --build .
